### ISSUE TITLE
Wound Resolution

### ISSUE THREAD

**Issue by lawfulstupid** [lawfulstupid/UESRPG-Combat-Helper#15]
- [x] Alter `NpcComponent.onHpChanges()` to accept a hit location
- [x] Display a message if damage taken (`NpcComponent.onHpChange()`) is in excess of WT.
- [x] Apply -20 penalty to NPC (requires #8)
- [x] Roll Shock test, automatically apply wound effects

**Comment by lawfulstupid** [comment]
Requires #11

**Comment by lawfulstupid** [comment]
- [x] Examine further wound effects to apply (requires #30)
- [x] Move hitLocationProperty to some temporary/transient properties class. Create new TemplateRole for such properties to indicate they should not be used on a DataCharacter.
- [x] Move shockTestProperty as well
- [x] Improve display of wounds

**Comment by lawfulstupid** [comment]
- [ ] Healing removes passive wound penalty for number of rounds equal to HP gained. Easiest to implement after #28 I think, by adding a new number field to property 'mutedForRounds', which decreases on new round event, and removed when it reaches 0. If you're doing that, might as well also add wound bleed out timer.

**Comment by lawfulstupid** [comment]
>Examine further wound effects to apply (requires #30)

Implemented as much as possible without #30. Everything else left as comments beginning `TODO #30`.

**Comment by lawfulstupid** [comment]
Moved remaining tasks to #34
